/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppContentPane: typeof import('./src/components/AppContentPane.vue')['default']
    BaseIcon: typeof import('./src/components/ui/BaseIcon.vue')['default']
    BaseToggle: typeof import('./src/components/ui/BaseToggle.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    HamburgerIcon: typeof import('./src/components/ui/HamburgerIcon.vue')['default']
    MantineSimpleFooter: typeof import('./src/components/footers/MantineSimpleFooter.vue')['default']
    MantineSimpleHeader: typeof import('./src/components/headers/MantineSimpleHeader.vue')['default']
    MantineSimpleNavbar: typeof import('./src/components/navbars/MantineSimpleNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/SectionHeader.vue')['default']
    SimpleHeader: typeof import('./src/components/headers/SimpleHeader.vue')['default']
    SimpleNavbar: typeof import('./src/components/navbars/SimpleNavbar.vue')['default']
    ThemeToggle: typeof import('./src/components/ui/ThemeToggle.vue')['default']
    TouchSlideoutDrawer: typeof import('./src/components/drawers/TouchSlideoutDrawer.vue')['default']
  }
}
